# Fly.io app configuration for PepperAI
# Uses the existing Dockerfile and runs Flask on port 5000

app = "pepperai"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  FLASK_ENV = "production"
  FLASK_DEBUG = "0"
  PYTHONUNBUFFERED = "1"
  PYTHONDONTWRITEBYTECODE = "1"
  # Leave REDIS_URL empty to disable Redis in single-app deploy
  REDIS_URL = ""
  # Paths are absolute in the image; volumes will be mounted here
  UPLOAD_FOLDER = "/app/uploads"
  RESULTS_FOLDER = "/app/results"
  # Use SQLite in instance folder by default
  DATABASE_URL = "sqlite:////app/instance/pepperai.db"
  MAX_CONTENT_LENGTH = "16777216"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    soft_limit = 50
    hard_limit = 100

# Define 3 persistent volume mounts for uploads, results, and instance (SQLite)
[[mounts]]
  source = "pepperai_uploads"
  destination = "/app/uploads"

[[mounts]]
  source = "pepperai_results"
  destination = "/app/results"

[[mounts]]
  source = "pepperai_instance"
  destination = "/app/instance"

[checks]
  [checks.http]
    port = 5000
    type = "http"
    method = "get"
    path = "/health"
    interval = "15s"
    timeout = "5s"
    grace_period = "30s"

# Machine sizing (adjust if needed)
[vm]
  memory = "2048mb"
  cpu_kind = "shared"
  cpus = 2


